### ISSUE TITLE
Feature idea: Ban using var

### ISSUE THREAD

**Issue by TenCoKaciStromy** [Aaronontheweb/EvilRoslynAnalyzers#26]
The evolution of C# is too fast. Some of the new features even reduce the LOC and removes whole level of pyramid of enterprise code (also know as pyramid of doom). That damages quartal bonuses based on newly writen LOC. The "flat" using statement is of them.

Wrong:
```
using var writer = new StreamWriter(...);
```
Correct:
```
using (var writer = new ...)
{
   ...
}
```

**Comment by Aaronontheweb** [comment]
Resolved, valiantly, via #30
